// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


// ...



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSlSJv-7ouXUi9t2ngI5j-2yRC_aN36_Q',
    appId: '1:801193133748:web:aa26fafe8520499faa79e1',
    messagingSenderId: '801193133748',
    projectId: 'flutterstudy-chike',
    authDomain: 'flutterstudy-chike.firebaseapp.com',
    storageBucket: 'flutterstudy-chike.appspot.com',
    measurementId: 'G-MX4X31T3YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNskMVsFdbaB3xCzauYBRJPVJEfjyb08M',
    appId: '1:801193133748:android:a8accd50b328e10aaa79e1',
    messagingSenderId: '801193133748',
    projectId: 'flutterstudy-chike',
    storageBucket: 'flutterstudy-chike.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT9ywUSgsbrmH_mUUzfPO-WSkZEuQrfYI',
    appId: '1:801193133748:ios:dc8ae6b35ec6cdd5aa79e1',
    messagingSenderId: '801193133748',
    projectId: 'flutterstudy-chike',
    storageBucket: 'flutterstudy-chike.appspot.com',
    iosBundleId: 'com.example.flutterstudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT9ywUSgsbrmH_mUUzfPO-WSkZEuQrfYI',
    appId: '1:801193133748:ios:f1401af98727b283aa79e1',
    messagingSenderId: '801193133748',
    projectId: 'flutterstudy-chike',
    storageBucket: 'flutterstudy-chike.appspot.com',
    iosBundleId: 'com.example.flutterstudy.RunnerTests',
  );
}
